export default {
  getMap(element) {
    return {
      id: element.id,
      certificate_type: element.certificate_type,
      certificate_type_label: element.certificate_type_label,
      correlative: element.correlative,
      client: element.client,
      client_data: element.client_data,
      lab: element.lab,
      lab_data: element.lab_data,
      equipment: element.equipment,
      brand: element.brand,
      model: element.model,
      serie: element.serie,
      indication_interval: element.indication_interval,
      identification_code: element.identification_code,
      calibration_date: element.calibration_date,
      emission_date: element.emission_date,
      uploaded_xls: element.uploaded_xls,
      signed_pdf: element.signed_pdf,
      billed: element.billed,
      billed_pdf: element.billed_pdf,
      sent: element.sent,
      sent_to: element.sent_to,
      sent_date: element.sent_date,
      observations: element.observations,
      registry_code: element.registry_code,
      attached_pdf: element.attached_pdf,
      uuid: element.uuid,
      uploaded: element.uploaded,
      payment_method: element.payment_method,
      payment_date: element.payment_date,
      payment_proof: element.payment_proof
    };
  },
  putMap(element) {
    return {
      id: element.id,
      certificate_type: element.certificate_type,
      correlative: element.correlative,
      client: element.client,
      lab: element.lab,
      equipment: element.equipment,
      brand: element.brand,
      model: element.model,
      serie: element.serie,
      indication_interval: element.indication_interval,
      identification_code: element.identification_code,
      calibration_date: element.calibration_date,
      emission_date: element.emission_date,
      uploaded_xls: element.uploaded_xls,
      signed_pdf: element.signed_pdf,
      billed: element.billed,
      billed_pdf: element.billed_pdf,
      sent: element.sent,
      sent_to: element.sent_to,
      sent_date: element.sent_date,
      observations: element.observations,
      uploaded: element.uploaded,
      payment_method: element.payment_method,
      payment_date: element.payment_date,
      payment_proof: element.payment_proof
    };
  }
};